# Generated by Django 3.2.7 on 2022-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220803_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rewards',
            field=models.IntegerField(default=10),
        ),
    ]
