# Generated by Django 3.2.7 on 2022-08-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pair',
        ),
        migrations.AddField(
            model_name='pair',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.task'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rewards',
            field=models.IntegerField(default=0),
        ),
    ]
