# Generated by Django 3.2.7 on 2022-08-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='complete',
            field=models.IntegerField(default=0),
        ),
    ]
