# Generated by Django 3.2.7 on 2022-08-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_pair_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
